### ISSUE TITLE
Use compiled regexes in C#

### ISSUE THREAD

**Issue by Horusiath** [mariomka/regex-benchmark#1]
While theoretically possible, in practice I've never found anyone using C# regexes via `Regex.Matches`. A standard practice here is to use `var reg = new Regex(@"[^a-zA-Z&-]+", RegexOptions.Compiled);`. Another case is the fact, that there seems to be no warmup phase for JITer compiler.

**Comment by mariomka** [comment]
I'm not very experienced with C#. I have tried with:

```cs
Regex regex = new Regex(pattern, RegexOptions.Compiled);
MatchCollection matches = regex.Matches(data);
```

```cs
MatchCollection matches = Regex.Matches(data, pattern, RegexOptions.Compiled);
```

And times are similar.

About JIT, I don't know how it works in C#.

Feel free to make a pull request if you want to improve any test.

**Comment by tupunco** [comment]
:(  sad..
