### ISSUE TITLE
Ruby benchmark compiles regexp before measuring

### ISSUE THREAD

**Issue by lopopolo** [mariomka/regex-benchmark#11]
A Regexp literal in Ruby, e.g. `/foo/` results in a call to `Regexp::compile`, which means the Regexp is already created by the time `measure` is invoked.

Instead, pass a String pattern that is compiled with `Regexp::compile`, which makes the test more analogous to the Rust one.

**Comment by mariomka** [comment]
Thank you, I have modified it. I will publish new results soon.
