### ISSUE TITLE
C++ benchmark improvements

### ISSUE THREAD

**Issue by bstaletic** [mariomka/regex-benchmark#16]
This repository came up in a recent C++ discussion in /r/cpp and once thing was immediately pointed out as wrong.

https://github.com/mariomka/regex-benchmark/blob/master/cpp/benchmark.cpp#L8-L16

You're measuring the time it takes to create the regex too, not just the loop.

Second, `std::regex` is known to be terribly slow and `boost::regex` is API compatible with much better performance. On top of that [CTRE](https://github.com/hanickadot/compile-time-regular-expressions/) is even faster.

Benchmarks on my computer, with C/PCRE for reference:

```
PCRE
bstaletic@Gallifrey c  (git)-[master]-% ./bin/benchmark ../input-text.txt
31.998263 - 92
26.271349 - 5301
7.516541 - 5

std::regex
bstaletic@Gallifrey cpp  (git)-[master]-% ./bin/benchmark ../input-text.txt
631.659 - 92
512.522 - 5301
391.858 - 5

boost::regex
bstaletic@Gallifrey cpp  (git)-[master]-% ./bin/benchmark ../input-text.txt
84.5532 - 92
86.0452 - 5301
34.0546 - 5

CTRE
bstaletic@Gallifrey cpp  (git)-[master]-% ./bin/benchmark ../input-text.txt
62.5399 - 92
52.8931 - 5301
12.9586 - 5
```

**Comment by mariomka** [comment]
I know, the benchmark isn't perfect but it can be useful in some situations. Performance can oscillate depending on the patterns, the input, the engine features...
It measures the time necessary to find the occurrences, and yes, it includes the regex creation for every language.
Maybe a benchmark measuring only the loop is interesting, but it isn't the objective of this.

About engines/libraries, I'm open to adding new implementations. If you want to add an implementation for `boost:regex` or `CTRE` please check the `Contributing` section in the readme.

Thank you.

**Comment by bstaletic** [comment]
> It measures the time necessary to find the occurrences, and yes, it includes the regex creation for every language.
Maybe a benchmark measuring only the loop is interesting, but it isn't the objective of this.

That's fair.

> About engines/libraries, I'm open to adding new implementations. If you want to add an implementation for `boost::regex` or `CTRE` please check the `Contributing` section in the readme.

`boost::regex` is just a namespace change (and needs `libboost_regex` installed in the docker image). I could make a pull request later today.

**Comment by mariomka** [comment]
Nice! Please, copy current implementation to `benchmark-boost.c`to maintain both implementations.
