### ISSUE TITLE
Use BenchmarkDotNet for C# Benchmark

### ISSUE THREAD

**Issue by c0shea** [mariomka/regex-benchmark#18]
I'd like to suggest that BenchmarkDotNet be used to perform the C# benchmark. There's a lot of overhead to running the C# executable once, as the JIT is doing a lot of upfront work coupled with the `RegexOptions.Compiled` flag.

Once the pump is primed, you'll notice that performance is better. I suppose it depends on what is trying to be measured, though. If it's to show the performance of running an executable that is trying to match the 3 regexes once and terminate, then the current approach works. However, this doesn't represent more typical usage in an application.

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i5-8500 CPU 3.00GHz (Coffee Lake), 1 CPU, 6 logical and 6 physical cores
.NET Core SDK=3.1.101
  [Host] : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT


```
|        Method |        Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 |  Allocated |
|-------------- |------------:|---------:|---------:|------:|------:|------:|-----------:|
|         Email | 1,357.77 ms | 2.984 ms | 2.791 ms |     - |     - |     - |  335.63 KB |
|           Uri | 1,175.25 ms | 3.274 ms | 3.063 ms |     - |     - |     - |  1402.2 KB |
|            Ip |    83.62 ms | 0.301 ms | 0.281 ms |     - |     - |     - |   19.65 KB |
| EmailCompiled |   964.28 ms | 2.583 ms | 2.416 ms |     - |     - |     - |  230.55 KB |
|   UriCompiled |   827.55 ms | 2.150 ms | 2.011 ms |     - |     - |     - | 1393.54 KB |
|    IpCompiled |    63.70 ms | 0.164 ms | 0.153 ms |     - |     - |     - |   15.11 KB |

``` cs

void Main()
{
    BenchmarkRunner.Run<RegexBenchmark>();
}

[MemoryDiagnoser]
public class RegexBenchmark
{
    private string _data;
    
    [GlobalSetup]
    public void GlobalSetup()
    {
        _data = File.ReadAllText(@"D:\Benchmarks\input-text.txt");
    }
    
    [Benchmark]
    public int Email()
    {
        MatchCollection matches = Regex.Matches(_data, @"[\w\.+-]+@[\w\.-]+\.[\w\.-]+");
        return matches.Count;
    }
    
    [Benchmark]
    public int Uri()
    {
        MatchCollection matches = Regex.Matches(_data, @"[\w]+://[^/\s?#]+[^\s?#]+(?:\?[^\s#]*)?(?:#[^\s]*)?");
        return matches.Count;
    }
    
    [Benchmark]
    public int Ip()
    {
        MatchCollection matches = Regex.Matches(_data, @"(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])");
        return matches.Count;
    }

    [Benchmark]
    public int EmailCompiled()
    {
        MatchCollection matches = Regex.Matches(_data, @"[\w\.+-]+@[\w\.-]+\.[\w\.-]+", RegexOptions.Compiled);
        return matches.Count;
    }

    [Benchmark]
    public int UriCompiled()
    {
        MatchCollection matches = Regex.Matches(_data, @"[\w]+://[^/\s?#]+[^\s?#]+(?:\?[^\s#]*)?(?:#[^\s]*)?", RegexOptions.Compiled);
        return matches.Count;
    }

    [Benchmark]
    public int IpCompiled()
    {
        MatchCollection matches = Regex.Matches(_data, @"(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])", RegexOptions.Compiled);
        return matches.Count;
    }
}

```

**Comment by Kryptos-FR** [comment]
I think you forgot to run against the input.

But anyway; the problem is that it also only check one scenario: executing a regex once on a very large input. There are other scenarii worth exploring like running the same regex multiple times on a smaller input (that could be a user input for example for validating an email field).

**Comment by c0shea** [comment]
@Kryptos-FR Good catch. No wonder it was so fast! I updated my post to the correct results testing on the input.

**Comment by DavidHulsman** [comment]
For general information:

[ltrzesniewski/pcre-net](https://github.com/ltrzesniewski/pcre-net) gives better performance for C#:

| Method        |        Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 |  Allocated |
| ------------- | ----------: | --------: | --------: | ----: | ----: | ----: | ---------: |
| Email         | 1,776.41 ms | 35.494 ms | 37.978 ms |     - |     - |     - |   21.04 KB |
| Uri           | 1,558.12 ms | 18.874 ms | 14.736 ms |     - |     - |     - | 1205.21 KB |
| Ip            |   122.41 ms |  2.445 ms |  6.734 ms |     - |     - |     - |    1.35 KB |
| EmailCompiled | 1,259.67 ms | 20.726 ms | 17.307 ms |     - |     - |     - |   22.85 KB |
| UriCompiled   | 1,168.96 ms | 25.686 ms | 74.519 ms |     - |     - |     - | 1205.21 KB |
| IpCompiled    |    98.06 ms |  1.943 ms |  5.415 ms |     - |     - |     - |    1.35 KB |
| EmailPCRE     |   219.82 ms |  3.491 ms |  3.265 ms |     - |     - |     - |   16.62 KB |
| UriPCRE       |   202.79 ms |  2.179 ms |  1.932 ms |     - |     - |     - |  911.67 KB |
| IpPCRE        |    28.27 ms |  0.377 ms |  0.334 ms |     - |     - |     - |    1.23 KB |

Using:

```Csharp
using PCRE;
using System.Linq;
using System.Collections.Generic;
```

and

```CSharp
var matches = PcreRegex.Matches(_data, @"[REGEX GOES HERE]");
return matches.Sum(item => item.Length);
```

Lets hope .NET 5 brings big improvements - Issue available here: https://github.com/dotnet/runtime/issues/23683

**Comment by BurntSushi** [comment]
> I suppose it depends on what is trying to be measured, though.

As far as I can tell, this benchmark is intentionally including the time it takes to compile the regex in addition to the search itself. So I'd imagine that "priming a JIT" or "initial overhead of the JIT" is fair game to be included in the measurement for this specific benchmark.

**Comment by mariomka** [comment]
Just to clarify, the benchmark is not perfect or an academic experiment. It simply measures the necessary time to find and count occurrences in a particular scenario.
I know, this scenario is no the best for all the engines or languages, it depends on default engine configuration (for example Unicode support) and language specs (for example JIT support).

Use BenchmarkDotNet seems to be fair to solve the problems you explained but it requires re-think the whole benchmark for all languages.

I'm able to receive improvement following the current implementation style but change how the benchmark works don't make sense for me right now.

Thank you for your thoughts and time.

**Comment by c0shea** [comment]
@mariomka Makes sense. Thanks!
