### ISSUE TITLE
There is a way to make rust regex compatible with normal regex syntax ? 

### ISSUE THREAD

**Issue by shachardevops** [mariomka/regex-benchmark#32]
@BurntSushi
```
fn measure(pattern: &str, data: &str) {
    let start = Instant::now();

    let regex = Regex::new(pattern);
    match regex {
        Ok(re) => {
            let count = re.find_iter(data).count();

            let elapsed = Instant::now().duration_since(start);
            println!("{} - {}", elapsed.as_secs_f64() * 1e3, count);
        }
        Err(err) => {
            println!("{:?}", err);
        }
    }
}
```
prints
```
regex parse error:
    .* x-x[[0-9]+] time="[0-9\.\:\-T]+" level=error msg="x x x x ([a-z0-9]{64}): x to x device ([a-z0-9]{64})-init:devicemapper: x x x x failed""
                                           ^^
error: unrecognized escape sequence
```
while other languages and online regex compile it just fine
**without changing the regex**

**Comment by BurntSushi** [comment]
Either change the regex for every benchmark or fix the benchmark rules to permit the change for Rust's case. The escapes being used are no-ops because they aren't special regex meta characters.

**Comment by BurntSushi** [comment]
Is that regex even part of this benchmark? What prompted you to file this issue?

**Comment by shachardevops** [comment]
This regex isn't part of the benchmark.. just a problem that I am trying to solve for a couple of days.
I have plenty of patterns that I can't change that I have a problem while using with rust.
what do you mean by 
fixing the patterns to permit the change for Rust's case

**Comment by shachardevops** [comment]
there is any flag or something to make rust regex to work with regexes like this? 
```  .* x-current[[0-9]+] time="[0-9\.\:\-T]+" level=error msg="x x x layer ([a-z0-9]{64}): failedxto remove x ([a-z0-9]{64})-x: Error running x x x""```
and another example
```
regex parse error:
    .*Container "(.*)" \({"d" "([0-9a-z]{64})"}\) of s (.*)_(.*)\((.*)\): s s s s\.\. s will be s and s.
                          ^
error: repetition quantifier expects a valid decimal
```

**Comment by BurntSushi** [comment]
@shachardevops I already answered your question here: https://github.com/rust-lang/regex/issues/727

Asking it again isn't going to produce a different answer.

**Comment by BurntSushi** [comment]
Although, I guess in that regex, your problem is that `{` _is_ a meta character and you aren't escaping it. That will never get fixed. Using it as a literal will always require an escape. I'd file a bug report against whatever source of regexes you're getting that from.

**Comment by shachardevops** [comment]
thanks
