### ISSUE TITLE
"C# benchmark" is incorrect: "RegexOptions.Compiled" "Flags" should not be set.

### ISSUE THREAD

**Issue by tupunco** [mariomka/regex-benchmark#5]
The `csharp` code in the `benchmark` is incorrect: `RegexOptions.Compiled` `Flags` should not be set.
 LINK: [csharp/Benchmark.cs#L33](https://github.com/mariomka/regex-benchmark/blob/master/csharp/Benchmark.cs#L33)

Because:
In many other languages, `Compile` is used as the `Parser` process for `Regex`. But on `.NET`, a `Compiled` option is provided to `dynamically` create `IL` objects, and the `vast majority of cases` should `not`  used. It is easy to be used incorrectly.

In addition, the `javascript` code used is unfair.
The `/...regex.../` syntax in `javascript` creates a `Regex` `instance object` that has been `Parser`, but the `Parser` consumption in other languages `Benchmark` is counted.

**Comment by mariomka** [comment]
It was be added after #1... but performance is similar. I'll remove the flag.

I've researched and I think that `Compiled` flag is doing nothing in .net core. By the way, `CompileToAssembly` isn't implemented either.

About `javascript`, I think you are right. I updated the test but performance is similar too.

Thank you.

**Comment by tupunco** [comment]
I have made a `serious` mistake. I used to think that the `regular engines` are much the same. Today, after careful testing and found that this is not true. 
`C#` benchmark speed is consumed in the `Match` process, rather than the `Parser` process.
It seems that `C#` regular engine is really too complicated to achieve,  the performance needs to be optimized.

**Comment by EgorBo** [comment]
@mariomka 
.NET Core 2.1 results.
With "Compile"
793.4948 - 92
670.5951 - 5301
65.6282 - 5

Without "Compile"
1115.553 - 92
931.4263 - 5301
75.4311 - 5

so Compile flag boosts it by 30-40%.
It's ignored in mono because we had an issue there and disabled it

**Comment by mariomka** [comment]
I have tried again and the results are similar but I have 2.0.0 I'll update and try again.

**Comment by mariomka** [comment]
I have updated dotnet to 2.1.4 and same results.

**Comment by Kryptos-FR** [comment]
Please reopen. Using `Compiled` option is obviously wrong. It only makes sense if you run the same regex (from the same run) more than a million times. And benchmarking using `Stopwatch` is just laughable.
