### ISSUE TITLE
some benchmarks in perl

### ISSUE THREAD

**Issue by bokutin** [mariomka/regex-benchmark#6]
<pre>
--> perl perl/benchmark.pl input-text.txt
213.690996 - 92
165.706158 - 5301
29.313803 - 5

--> perl perl/benchmark_bytes.pl input-text.txt
95.394135 - 92
62.829971 - 5301
24.369955 - 5

--> perl perl/benchmark_bytes_ascii.pl input-text.txt
57.080984 - 92
62.375784 - 5301
24.430990 - 5

--> perl perl/benchmark_bytes_ascii_nocapture.pl input-text.txt
57.039022 - 92
62.216997 - 5301
24.269104 - 5

--> uname -v
FreeBSD 11.1-RELEASE-p1 #0: Wed Aug  9 11:55:48 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC

--> perl -E 'say $^V'
v5.26.1

--> diff -u perl/benchmark.pl perl/benchmark_bytes.pl
--- perl/benchmark.pl   2017-10-22 14:08:18.000000000 +0900
+++ perl/benchmark_bytes.pl     2017-10-22 14:30:27.000000000 +0900
@@ -18,7 +18,7 @@

 my ($filename) = @ARGV;

-open my $fh, '<:encoding(UTF-8)', $filename or die 'Could not open file.';
+open my $fh, '<', $filename or die 'Could not open file.';
 my $text;
 read $fh, $data, -s $filename;
 close $fh;

--> diff -u perl/benchmark_bytes.pl perl/benchmark_bytes_ascii.pl
--- perl/benchmark_bytes.pl     2017-10-22 14:30:27.000000000 +0900
+++ perl/benchmark_bytes_ascii.pl       2017-10-22 14:30:33.000000000 +0900
@@ -5,7 +5,7 @@

     my $start = Time::HiRes::gettimeofday();

-    my $count = () = $data =~ /$pattern/g;
+    my $count = () = $data =~ /$pattern/ga;

     my $elapsed = (Time::HiRes::gettimeofday() - $start) * 1e3;

--> diff -u perl/benchmark_bytes_ascii.pl perl/benchmark_bytes_ascii_nocapture.pl
--- perl/benchmark_bytes_ascii.pl       2017-10-22 14:30:33.000000000 +0900
+++ perl/benchmark_bytes_ascii_nocapture.pl     2017-10-22 14:52:44.183470000 +0900
@@ -5,7 +5,7 @@

     my $start = Time::HiRes::gettimeofday();

-    my $count = () = $data =~ /$pattern/ga;
+    my $count = () = $data =~ /$pattern/gan;

     my $elapsed = (Time::HiRes::gettimeofday() - $start) * 1e3;
</pre>

**Comment by mariomka** [comment]
I have updated the Perl benchmark reading file without UTF8 encoding. Thank you.
