### ISSUE TITLE
Why Python is faster than Go and C#?

### ISSUE THREAD

**Issue by hsluoyz** [mariomka/regex-benchmark#8]
Python is a dynamic language. Go is a static language. There is no way that Go is slower than Python.

And C# is similar to Java in the runtime. So C# should at least faster than Python too.

**Comment by mariomka** [comment]
It seems that Go does not have the best implementation, you can find some issues related in the golang repo.
.Net **Core** has no compiled regex the performance is worse than in .Net.

By the way, you can run all the benchmarks in your system. In the next days, when I have time, I will add benchmark for Dart and I will run all the benchmarks again in a new machine.

From README:
> I hope this benchmark can be helpful for choosing a language but it's not only about performance, each language has its engine and offers different features (like UTF support, backreferences, capturing groups...)
